spring:
  application:
    name: rag-observer-sentinel
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: phi3

management:
  otlp:
    tracing:
      endpoint: http://localhost:4317
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus