apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # access: proxy - Grafana backend routes the requests (standard for Docker)
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    # editable: false - prevents someone from accidentally breaking it in the UI
    editable: false